<?php
namespace Cnab;

class Movimento
{
    const REMESSA_ENTRADA_DE_TITULO                                     = 1;
    const REMESSA_PEDIDO_DE_BAIXA                                       = 2;
    const REMESSA_CONCESSAO_DE_ABATIMENTO                               = 4;
    const REMESSA_CANCELAMENTO_DE_ABATIMENTO                            = 5;
    const REMESSA_ALTERACAO_DE_VENCIMENTO                               = 6;
    const REMESSA_CONCESSAO_DE_DESCONTO                                 = 7;
    const REMESSA_CANCELAMENTO_DE_DESCONTO                              = 8;
    const REMESSA_PROTESTAR                                             = 9;
    const REMESSA_SUSTAR_PROTESTO_E_BAIXAR_TITULO                       = 10;
    const REMESSA_SUSTAR_PROTESTO_E_MANTER_EM_CARTEIRA                  = 11;
    const REMESSA_ALTERACAO_DE_JUROS_DE_MORA                            = 12;
    const REMESSA_DISPENSAR_COBRANCA_DE_JUROS_DE_MORA                   = 13;
    const REMESSA_ALTERACAO_DE_VALOR_OU_PERCENTUAL_DE_MULTA             = 14;
    const REMESSA_DISPENSAR_COBRANCA_DE_MULTA                           = 15;
    const REMESSA_ALTERACAO_DO_VALOR_DE_DESCONTO                        = 16;
    const REMESSA_NAO_CONCEDER_DESCONTO                                 = 17;
    const REMESSA_ALTERACAO_DO_VALOR_DE_ABATIMENTO                      = 18;
    const REMESSA_ALTERACAO_DE_OUTROS_DADOS                             = 31;
    const REMESSA_ALTERACAO_DOS_DADOS_DO_RATEIO_DE_CREDITO              = 33;
    const REMESSA_PEDIDO_DE_CANCELAMENTO_DOS_DADOS_DO_RATEIO_DE_CREDITO = 34;
    const REMESSA_INCLUSAO_NO_BANCO_DE_PAGADORES                        = 36;
    const REMESSA_ALTERACAO_NO_BANCO_DE_PAGADORES                       = 37;
    const REMESSA_EXCLUSAO_NO_BANCO_DE_PAGADORES                        = 38;
    const REMESSA_SERVICOS                                              = 40;
    const REMESSA_ALTERACAO_DO_VALOR_NOMINAL_DO_TITULO                  = 47;
    const REMESSA_ALTERACAO_VALOR_OU_PERCENTUAL_MINIMO_OU_MAXIMO        = 48;

    const RETORNO_SOLICITACAO_DE_IMPRESSAO_DE_TITULOS_CONFIRMADA_CEF        = 1;
    const RETORNO_ENTRADA_CONFIRMADA                                        = 2;
    const RETORNO_ENTRADA_REJEITADA                                         = 3;
    const RETORNO_TRANSFERENCIA_DE_CONTRATO                                 = 4;
    const RETORNO_TRANSFERENCIA_DE_CARTEIRA_BAIXA                           = 5;
    const RETORNO_LIQUIDACAO                                                = 6;
    const RETORNO_CONFIRMACAO_DA_INSTRUCAO_DE_DESCONTO                      = 7;
    const RETORNO_CONFIRMACAO_DO_CANCELAMENTO_DA_INSTRUCAO_DE_DESCONTO      = 8;
    const RETORNO_BAIXA                                                     = 9;
    const RETORNO_TITULO_EM_CARTEIRA                                        = 11;
    const RETORNO_CONFIRMACAO_DE_ABATIMENTO                                 = 12;
    const RETORNO_ABATIMENTO_CANCELADO                                      = 13;
    const RETORNO_ALTERACAO_DE_VENCIMENTO                                   = 14;
    const RETORNO_LIQUIDACAO_EM_CARTORIO                                    = 15;
    const RETORNO_LIQUIDACAO_APOS_BAIXA_OU_LIQUIDACAO_TITULO_NAO_REGISTRADO = 17;
    const RETORNO_CONFIRMACAO_DE_INSTRUCAO_DE_PROTESTO                      = 19;
    const RETORNO_CONFIRMACAO_DE_INSTRUCAO_DE_SUSTACAO_DE_PROTESTO          = 20;
    const RETORNO_REMESSA_A_CARTORIO_CEF                                    = 23;
    const RETORNO_RETIRADA_DE_CARTORIO                                      = 24;
    const RETORNO_PROTESTADO_E_BAIXADO                                      = 25;
    const RETORNO_INSTRUCAO_REJEITADA                                       = 26;
    const RETORNO_CONFIRMACAO_DO_PEDIDO_DE_ALTERACAO_DE_OUTROS_DADOS        = 27;
    const RETORNO_DEBITO_DE_TARIFAS_CUSTAS                                  = 28;
    const RETORNO_ALTERACAO_DE_DADOS_REJEITADA                              = 30;
    const RETORNO_CONFIRMACAO_DE_INCLUSAO_BANCO_DE_PAGADOR_CEF              = 35;
    const RETORNO_CONFIRMACAO_DE_ALTERACAO_BANCO_DE_PAGADOR_CEF             = 36;
    const RETORNO_CONFIRMACAO_DE_EXCLUSAO_BANCO_DE_PAGADOR_CEF              = 37;
    const RETORNO_EMISSAO_DE_BOLETOS_DE_BANCO_DE_PAGADOR_CEF                = 38;
    const RETORNO_MANUTENCAO_DE_PAGADOR_REJEITADA_CEF                       = 39;
    const RETORNO_ENTRADA_DE_TITULO_VIA_BANCO_DE_PAGADOR_REJEITADA_CEF      = 40;
    const RETORNO_MANUTENCAO_DE_BANCO_DE_PAGADOR_REJEITADA_CEF              = 41;
    const RETORNO_ESTORNO_DE_BAIXA_LIQUIDACAO_CEF                           = 44;
    const RETORNO_ALTERACAO_DE_DADOS_CEF                                    = 45;
    const RETORNO_LIQUIDACAO_ON_LINE_CEF                                    = 46;
    const RETORNO_ESTORNO_DE_LIQUIDACAO_ON_LINE_CEF                         = 47;
    const RETORNO_TITULO_DDA_RECONHECIDO_PELO_PAGADOR_CEF                   = 51;
    const RETORNO_TITULO_DDA_NAO_RECONHECIDO_PELO_PAGADOR_CEF               = 52;
    const RETORNO_TITULO_DDA_RECUSADO_PELA_CIP_CEF                          = 53;
    const RETORNO_CONFIRMACAO_DE_ALTERACAO_DO_VALOR_NOMINAL_DO_TITULO_CEF   = 61;
}